### ISSUE TITLE
最新版材質包在材質包列表找不到

### ISSUE THREAD

**Issue by Kayxue** [The-Cat-Town-Craft/TCTC-Cherry#1]
如題，已嘗試過 20240225 一般版本，安裝後在材質包列表有顯示該材質包，但最新 20240329 版安裝後，材質包列表中卻找不到此材質包，但貓爪包安裝後是找得到的， Minecraft 版本為 1.20.4
<img width="1680" alt="Screenshot 2024-05-29 at 5 19 08 PM" src="https://github.com/The-Cat-Town-Craft/TCTC-Cherry/assets/26020165/2950f7a1-988e-4f8d-83bd-bc442765c0d9">

**Comment by NakiriRuri** [comment]
你能在文件夹里存在这个包的情况下启动一次游戏，然后发一下这次启动产生的latest.log吗？

**Comment by Kayxue** [comment]
[latest.log](https://github.com/The-Cat-Town-Craft/TCTC-Cherry/files/15494768/latest.log)

**Comment by Kayxue** [comment]
Folder View 下看不到該材質包，但剛剛我有切 Flat View，看得到檔案
但是加入後按完成他會爆 Resource Reload Failed
<img width="1680" alt="Screenshot 2024-05-30 at 2 46 01 PM" src="https://github.com/The-Cat-Town-Craft/TCTC-Cherry/assets/26020165/497cd277-3d89-423b-9b4b-4ade6d62bb1a">

**Comment by NakiriRuri** [comment]
- 你有一个改动过资源包读取的模组，它好像在拒绝读取资源包识别文件 “pack.mcmeta” 中的 overlays 字段，不止我的包在报错， 
其他包也在报；
这个字段是 1.20.2 之后 MC 新增的功能，我用来实现多版本兼容和文件管理。我建议你禁用这个模组，或者去作者那边去反馈一下；
 - 加载资源包报 "Resource Reload Failed"，合理怀疑是选择框改色功能的原版 Shader 在 MacOS 上不可用；
 在我这边至少 1.17 - 1.20.4 是可用的，我测试过这几个版本的原版或者是加装 Sodium 都是可用状态，OptiFine 情况下未测试；
这边建议的修复是，删除资源包里面 16_23_compat/assets/minecraft/shaders 这个文件夹；
