### ISSUE TITLE
音符盒材质故障

### ISSUE THREAD

**Issue by aaa-qwq-123** [The-Cat-Town-Craft/TCTC-Cherry#2]
![image](https://github.com/user-attachments/assets/0a5d1f03-eb73-4991-a436-037c3c7abe91)
感觉像是坏了一半，有原来的纹理但是也有错误贴图
吧其他材质卸了就全是错误贴图了
![image](https://github.com/user-attachments/assets/43152598-d5d1-416a-845a-77d977bd9cc8)

**Comment by NakiriRuri** [comment]
所以你的材质列表是什么，我要去复现。
