### ISSUE TITLE
红石粉颜色错误

### ISSUE THREAD

**Issue by class5class** [The-Cat-Town-Craft/TCTC-Cherry#4]
![image](https://github.com/user-attachments/assets/73ff1895-ebb2-4b13-b2ce-eec86214d0ae)
# 使用cherry wire模组或polytone模组，一些情况下特别强度的红石粉会成为暗蓝色或者红色，图中添加了meow附加包

**Comment by NakiriRuri** [comment]
我现在暂时没精力维护猫爪附加包以及修复它相关的问题，等我有时间后再看看这个包如何做成原版可用的改色而不依赖模组。
